config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "opinions#index"
  resources :opinions, except: [:show]
  resources :followings, only: [:index, :create, :destroy]
  resources :favorites, only: [:index, :create, :destroy]
  resources :users, only: [:show, :destroy]

  get 'trends', to: "opinions#trends"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { in: 5..20 }

  has_many :opinions, foreign_key: :author_id, dependent: :destroy

  has_many :favorites, foreign_key: :user_id, dependent: :destroy
  has_many :favorite_opinions, through: :favorites, source: :opinion

  has_many :followings, foreign_key: :follower_id, dependent: :destroy
  has_many :followed_users, through: :followings, source: :followed

  has_many :inverse_followings, class_name: 'Following', foreign_key: :followed_id, dependent: :destroy
  has_many :followers, through: :inverse_followings, source: :follower

  has_one_attached :photo

  has_one_attached :cover_image

  def prof_pic_attached
    photo.attached? ? photo : 'prof-pic.jpg'
  end

  def cover_pic_attached
    cover_image.attached? ? cover_image : 'cover-img.jpg'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @users = User.includes(:followers, :followed_users, :opinions, :favorites)
    @user = @users.find_by(id: params[:id])
    @followed_by = @user.followers.where.not(id: current_user.id).take(10)
    @opinion = Opinion.new
  end
end

app/helpers/user_helper.rb
module UserHelper
  def to_follow
    ids = current_user.followed_users.pluck(:id) << current_user.id
    User.where.not(id: ids).take(15)
  end

  def follow_btns(user)
    if user != current_user
      if !current_user.followed_users.include?(user)
        link_to('Follow', followings_path(id: user.id), class: 'btn btn-primary btn-sm', method: :post)
      else
        link_to('Unfollow', following_path(id: user.id), class: 'btn btn-secondary btn-sm', method: :delete)
      end
    else
      link_to('Edit your profile', edit_user_registration_path(user), class: 'btn btn-success btn-sm')
    end
  end
end

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row justify-content-between">
    <div class="col-lg-8 px-0">
      <%= image_tag(@user.cover_pic_attached, class: 'd-block w-100 cover-img mb-4') %>
      <%= show_form(@user) %>
      <h1 class="all-op text-uppercase font-weight-bold white-backg py-3 px-2"><%= "#{@user.name}'s opinions"%></h1>
      <%= render partial: "shared/opinion-show", locals: {opinions: @user.opinions.most_recent_opinions} %>
    </div>
    <div class="col-lg-4 d-flex justify-content-center my-0">
      <div class="user-show white-backg pt-5">
        <%= image_tag(@user.prof_pic_attached, class: 'prof-img d-block mx-auto rounded-circle') %>
        <h3 class="text-center user-name font-weight-bold pt-3"> <%= @user.name %> <h3>
        <div class="text-center">
          <%= follow_btns(@user)%>
        </div>
        <div class="row mx-0 mt-3 border-bottom border-top">
          <div class="col-lg-3 border-right px-0">
            <p class="counts text-center font-weight-bold mt-2"> 
              <%= @user.opinions.count %> 
            </p>
            <p class="text-center counts-text text-capitalize font-weight-bold"> 
              <%= link_to('opinions', user_path(@user))%> 
            </p>
          </div>
          <div class="col-lg-3 border-right px-0">
            <p class="counts text-center font-weight-bold mt-2"> 
              <%= @user.followers.count %> 
            </p>
            <p class="text-center counts-text text-capitalize font-weight-bold"> 
              <%= link_to('followers', followings_path(user_id: @user.id, users: "followers"))%> 
            </p>
          </div>
          <div class="col-lg-3 border-right px-0">
            <p class="counts text-center font-weight-bold mt-2"> 
              <%= @user.followed_users.count %> 
            </p>
            <p class="text-center counts-text text-capitalize font-weight-bold"> 
              <%= link_to('following', followings_path(user_id: @user.id, users: "followings"))%> 
            </p>
          </div>
          <div class="col-lg-3 px-0">
            <p class="counts text-center font-weight-bold mt-2"> 
              <%= @user.favorites.count %> 
            </p>
            <p class="text-center counts-text text-capitalize font-weight-bold"> 
              <%= link_to('favorites', favorites_path(user_id: @user.id))%>
            </p>
          </div>
        </div>
        <p class="font-weight-bold text-center section-head my-4 text-uppercase"> Followed by </p>
        <%= render partial: "shared/who-to-follow", locals: {users: @followed_by}%>
      </div>
    </div>
  </div>
</div>